package com.conjuntos.espin.mail;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.Serializable;
import java.nio.ByteBuffer;
import java.nio.charset.Charset;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.ejb.LocalBean;
import javax.ejb.Stateless;

@LocalBean
@Stateless
public class MailTool implements Serializable {

    private static final Logger log = Logger.getLogger(MailTool.class.getName());

    private static String name;
    private static String link;
    private static String userName;

    public void init(String _name, String _link) {
        name = _name;
        link = _link;
    }

    public void init(String _name, String _link, String _userName) {
        name = _name;
        link = _link;
        userName = _userName;
    }

    public Boolean sendEmail(String receiver, String Nomnbre, String Lugar, String Asunto, String Forma, String Valor, String Fecha) {
        Boolean success = false;
        try {
            SendEmail sendEmail = new SendEmail();
            sendEmail.setDestinatario(receiver);
            sendEmail.setSubject("Notificación TU HOGAR");
            sendEmail.setSubject("Correo de Confirmación");
            init("TU HOGAR", "ningun link");
            sendEmail.setMensaje(getMessageComprobante(Nomnbre, Asunto, Lugar, Forma, Valor, Fecha));
            sendEmail.cargarConfiguracion();
            success = sendEmail.enviarCorreo();
        } catch (Exception ex) {
            log.log(Level.SEVERE, "No se envio el correo electrónico.", ex);
            success = false;
        }

        return success;
    }

    private String getMessageComprobante(String Nomnbre, String Asunto, String Lugar, String Forma, String Valor, String Fecha) throws Exception {
        String message = "";
        try {
            String url = "/var/www/html/mail/mail_cmp.html";
            Path path = Paths.get(url);
            BufferedWriter bw = null;
            FileWriter fw = null;
            //if directory exists?
            if (!Files.exists(path)) {
                Files.createDirectories(path);
                File file = new File(url);
                FileOutputStream fop = fop = new FileOutputStream(file);
                String html = this.getHTML();
                byte[] contentInBytes = html.getBytes();
                fop.write(contentInBytes);
                fop.flush();
                fop.close();
                fw = new FileWriter(url);
                bw = new BufferedWriter(fw);
                bw.write(this.getHTML());
                if (bw != null) {
                    bw.close();
                }

                if (fw != null) {
                    fw.close();
                }
                log.log(Level.INFO, "Directory is created!");
            }
            String html = this.getHTML();
            byte[] encoded = Files.readAllBytes(path);
            Charset encoding = Charset.forName("UTF-8");
            message = encoding.decode(ByteBuffer.wrap(encoded)).toString();
            message = message.replaceAll("XNombreX", Nomnbre);
            message = message.replaceAll("XLugarX", Lugar);
            message = message.replaceAll("XAsuntoX", Asunto);
            message = message.replaceAll("XFormaX", Forma);
            message = message.replaceAll("XValorX", Valor);
            message = message.replaceAll("XFechaX", Fecha);

        } catch (IOException ex) {
            log.log(Level.SEVERE, "No se pudo leer el archivo. IO Exception: ", ex);
            throw ex;
        }
        return message;
    }

    private String getHTML() {
        String html = "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Strict//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd\">\n"
                + "<html xmlns=\"http://www.w3.org/1999/xhtml\">\n"
                + "    <head>\n"
                + "        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\n"
                + "        <meta name=\"viewport\" content=\"width=device-width\"/>\n"
                + "        <style>\n"
                + "            /**********************************************\n"
                + "            * Ink v1.0.5 - Copyright 2013 ZURB Inc        *\n"
                + "            **********************************************/\n"
                + "\n"
                + "            /* Client-specific Styles & Reset */\n"
                + "\n"
                + "            #outlook a { \n"
                + "                padding:0; \n"
                + "            } \n"
                + "\n"
                + "            body{ \n"
                + "                width:100% !important; \n"
                + "                min-width: 100%;\n"
                + "                -webkit-text-size-adjust:100%; \n"
                + "                -ms-text-size-adjust:100%;\n"
                + "                -moz-text-size-adjust:100%;\n"
                + "                margin:0; \n"
                + "                padding:0;\n"
                + "            }\n"
                + "\n"
                + "            .ExternalClass { \n"
                + "                width:100%;\n"
                + "            } \n"
                + "\n"
                + "            .ExternalClass, \n"
                + "            .ExternalClass p, \n"
                + "            .ExternalClass span, \n"
                + "            .ExternalClass font, \n"
                + "            .ExternalClass td, \n"
                + "            .ExternalClass div { \n"
                + "                line-height: 100%; \n"
                + "            } \n"
                + "\n"
                + "            #backgroundTable { \n"
                + "                margin:0; \n"
                + "                padding:0; \n"
                + "                width:100% !important; \n"
                + "                line-height: 100% !important; \n"
                + "            }\n"
                + "\n"
                + "            img { \n"
                + "                outline:none; \n"
                + "                text-decoration:none; \n"
                + "                -ms-interpolation-mode: bicubic;\n"
                + "                width: auto;\n"
                + "                max-width: 100%; \n"
                + "                float: left; \n"
                + "                clear: both; \n"
                + "                display: block;\n"
                + "            }\n"
                + "\n"
                + "            center {\n"
                + "                width: 100%;\n"
                + "                min-width: 580px;\n"
                + "            }\n"
                + "\n"
                + "            a img { \n"
                + "                border: none;\n"
                + "            }\n"
                + "\n"
                + "            p {\n"
                + "                margin: 0 0 0 10px;\n"
                + "            }\n"
                + "\n"
                + "            table {\n"
                + "                border-spacing: 0;\n"
                + "                border-collapse: collapse;\n"
                + "            }\n"
                + "\n"
                + "            td { \n"
                + "                word-break: break-word;\n"
                + "                -webkit-hyphens: auto;\n"
                + "                -moz-hyphens: auto;\n"
                + "                hyphens: auto;\n"
                + "                border-collapse: collapse !important; \n"
                + "            }\n"
                + "\n"
                + "            table, tr, td {\n"
                + "                padding: 0;\n"
                + "                vertical-align: top;\n"
                + "                text-align: left;\n"
                + "            }\n"
                + "\n"
                + "            hr {\n"
                + "                color: #d9d9d9; \n"
                + "                background-color: #d9d9d9; \n"
                + "                height: 1px; \n"
                + "                border: none;\n"
                + "            }\n"
                + "\n"
                + "            /* Responsive Grid */\n"
                + "\n"
                + "            table.body {\n"
                + "                height: 100%;\n"
                + "                width: 100%;\n"
                + "            }\n"
                + "\n"
                + "            table.container {\n"
                + "                width: 580px;\n"
                + "                margin: 0 auto;\n"
                + "                text-align: inherit;\n"
                + "            }\n"
                + "\n"
                + "            table.row {\n"
                + "                padding: 0px;\n"
                + "                width: 100%;\n"
                + "                position: relative;\n"
                + "                background-color: #ECF8FF;\n"
                + "            }\n"
                + "\n"
                + "            table.container table.row {\n"
                + "                display: block;\n"
                + "            }\n"
                + "\n"
                + "            td.wrapper {\n"
                + "                padding: 10px 20px 0px 0px;\n"
                + "                position: relative;\n"
                + "            }\n"
                + "\n"
                + "            table.columns,\n"
                + "            table.column {\n"
                + "                margin: 0 auto;\n"
                + "            }\n"
                + "\n"
                + "            table.columns td,\n"
                + "            table.column td {\n"
                + "                padding: 0px 0px 10px; \n"
                + "            }\n"
                + "\n"
                + "            table.columns td.sub-columns,\n"
                + "            table.column td.sub-columns,\n"
                + "            table.columns td.sub-column,\n"
                + "            table.column td.sub-column {\n"
                + "                padding-right: 10px;\n"
                + "            }\n"
                + "\n"
                + "            td.sub-column, td.sub-columns {\n"
                + "                min-width: 0px;\n"
                + "            }\n"
                + "\n"
                + "            table.row td.last,\n"
                + "            table.container td.last {\n"
                + "                padding-right: 0px;\n"
                + "            }\n"
                + "\n"
                + "            table.one { width: 30px; }\n"
                + "            table.two { width: 80px; }\n"
                + "            table.three { width: 130px; }\n"
                + "            table.four { width: 180px; }\n"
                + "            table.five { width: 230px; }\n"
                + "            table.six { width: 280px; }\n"
                + "            table.seven { width: 330px; }\n"
                + "            table.eight { width: 380px; }\n"
                + "            table.nine { width: 430px; }\n"
                + "            table.ten { width: 480px; }\n"
                + "            table.eleven { width: 530px; }\n"
                + "            table.twelve { width: 580px; }\n"
                + "\n"
                + "            table.one center { min-width: 30px; }\n"
                + "            table.two center { min-width: 80px; }\n"
                + "            table.three center { min-width: 130px; }\n"
                + "            table.four center { min-width: 180px; }\n"
                + "            table.five center { min-width: 230px; }\n"
                + "            table.six center { min-width: 280px; }\n"
                + "            table.seven center { min-width: 330px; }\n"
                + "            table.eight center { min-width: 380px; }\n"
                + "            table.nine center { min-width: 430px; }\n"
                + "            table.ten center { min-width: 480px; }\n"
                + "            table.eleven center { min-width: 530px; }\n"
                + "            table.twelve center { min-width: 580px; }\n"
                + "\n"
                + "            table.one .panel center { min-width: 10px; }\n"
                + "            table.two .panel center { min-width: 60px; }\n"
                + "            table.three .panel center { min-width: 110px; }\n"
                + "            table.four .panel center { min-width: 160px; }\n"
                + "            table.five .panel center { min-width: 210px; }\n"
                + "            table.six .panel center { min-width: 260px; }\n"
                + "            table.seven .panel center { min-width: 310px; }\n"
                + "            table.eight .panel center { min-width: 360px; }\n"
                + "            table.nine .panel center { min-width: 410px; }\n"
                + "            table.ten .panel center { min-width: 460px; }\n"
                + "            table.eleven .panel center { min-width: 510px; }\n"
                + "            table.twelve .panel center { min-width: 560px; }\n"
                + "\n"
                + "            .body .columns td.one,\n"
                + "            .body .column td.one { width: 8.333333%; }\n"
                + "            .body .columns td.two,\n"
                + "            .body .column td.two { width: 16.666666%; }\n"
                + "            .body .columns td.three,\n"
                + "            .body .column td.three { width: 25%; }\n"
                + "            .body .columns td.four,\n"
                + "            .body .column td.four { width: 33.333333%; }\n"
                + "            .body .columns td.five,\n"
                + "            .body .column td.five { width: 41.666666%; }\n"
                + "            .body .columns td.six,\n"
                + "            .body .column td.six { width: 50%; }\n"
                + "            .body .columns td.seven,\n"
                + "            .body .column td.seven { width: 58.333333%; }\n"
                + "            .body .columns td.eight,\n"
                + "            .body .column td.eight { width: 66.666666%; }\n"
                + "            .body .columns td.nine,\n"
                + "            .body .column td.nine { width: 75%; }\n"
                + "            .body .columns td.ten,\n"
                + "            .body .column td.ten { width: 83.333333%; }\n"
                + "            .body .columns td.eleven,\n"
                + "            .body .column td.eleven { width: 91.666666%; }\n"
                + "            .body .columns td.twelve,\n"
                + "            .body .column td.twelve { width: 100%; }\n"
                + "\n"
                + "            td.offset-by-one { padding-left: 50px; }\n"
                + "            td.offset-by-two { padding-left: 100px; }\n"
                + "            td.offset-by-three { padding-left: 150px; }\n"
                + "            td.offset-by-four { padding-left: 200px; }\n"
                + "            td.offset-by-five { padding-left: 250px; }\n"
                + "            td.offset-by-six { padding-left: 300px; }\n"
                + "            td.offset-by-seven { padding-left: 350px; }\n"
                + "            td.offset-by-eight { padding-left: 400px; }\n"
                + "            td.offset-by-nine { padding-left: 450px; }\n"
                + "            td.offset-by-ten { padding-left: 500px; }\n"
                + "            td.offset-by-eleven { padding-left: 550px; }\n"
                + "\n"
                + "            td.expander {\n"
                + "                visibility: hidden;\n"
                + "                width: 0px;\n"
                + "                padding: 0 !important;\n"
                + "            }\n"
                + "\n"
                + "            table.columns .text-pad,\n"
                + "            table.column .text-pad {\n"
                + "                padding-left: 10px;\n"
                + "                padding-right: 10px;\n"
                + "            }\n"
                + "\n"
                + "            table.columns .left-text-pad,\n"
                + "            table.columns .text-pad-left,\n"
                + "            table.column .left-text-pad,\n"
                + "            table.column .text-pad-left {\n"
                + "                padding-left: 10px;\n"
                + "            }\n"
                + "\n"
                + "            table.columns .right-text-pad,\n"
                + "            table.columns .text-pad-right,\n"
                + "            table.column .right-text-pad,\n"
                + "            table.column .text-pad-right {\n"
                + "                padding-right: 10px;\n"
                + "            }\n"
                + "\n"
                + "            /* Block Grid */\n"
                + "\n"
                + "            .block-grid {\n"
                + "                width: 100%;\n"
                + "                max-width: 580px;\n"
                + "            }\n"
                + "\n"
                + "            .block-grid td {\n"
                + "                display: inline-block;\n"
                + "                padding:10px;\n"
                + "            }\n"
                + "\n"
                + "            .two-up td {\n"
                + "                width:270px;\n"
                + "            }\n"
                + "\n"
                + "            .three-up td {\n"
                + "                width:173px;\n"
                + "            }\n"
                + "\n"
                + "            .four-up td {\n"
                + "                width:125px;\n"
                + "            }\n"
                + "\n"
                + "            .five-up td {\n"
                + "                width:96px;\n"
                + "            }\n"
                + "\n"
                + "            .six-up td {\n"
                + "                width:76px;\n"
                + "            }\n"
                + "\n"
                + "            .seven-up td {\n"
                + "                width:62px;\n"
                + "            }\n"
                + "\n"
                + "            .eight-up td {\n"
                + "                width:52px;\n"
                + "            }\n"
                + "\n"
                + "            /* Alignment & Visibility Classes */\n"
                + "\n"
                + "            table.center, td.center {\n"
                + "                text-align: center;\n"
                + "            }\n"
                + "\n"
                + "            h1.center,\n"
                + "            h2.center,\n"
                + "            h3.center,\n"
                + "            h4.center,\n"
                + "            h5.center,\n"
                + "            h6.center {\n"
                + "                text-align: center;\n"
                + "            }\n"
                + "\n"
                + "            span.center {\n"
                + "                display: block;\n"
                + "                width: 100%;\n"
                + "                text-align: center;\n"
                + "            }\n"
                + "\n"
                + "            img.center {\n"
                + "                margin: 0 auto;\n"
                + "                float: none;\n"
                + "            }\n"
                + "\n"
                + "            .show-for-small,\n"
                + "            .hide-for-desktop {\n"
                + "                display: none;\n"
                + "            }\n"
                + "\n"
                + "            /* Typography */\n"
                + "\n"
                + "            body, table.body, h1, h2, h3, h4, h5, h6, p, td { \n"
                + "                color: #222222;\n"
                + "                font-family: \"Helvetica\", \"Arial\", sans-serif; \n"
                + "                font-weight: normal; \n"
                + "                padding:0; \n"
                + "                margin: 0;\n"
                + "                text-align: left; \n"
                + "                line-height: 1.3;\n"
                + "            }\n"
                + "\n"
                + "            h1, h2, h3, h4, h5, h6 {\n"
                + "                word-break: normal;\n"
                + "            }\n"
                + "\n"
                + "            h1 {\n"
                + "                font-size: 30px;\n"
                + "            }\n"
                + "            h2 {font-size: 36px;}\n"
                + "            h3 {font-size: 32px;}\n"
                + "            h4 {font-size: 28px;}\n"
                + "            h5 {font-size: 24px;}\n"
                + "            h6 {font-size: 20px;}\n"
                + "            body, table.body, p, td {font-size: 14px;line-height:19px;}\n"
                + "\n"
                + "            p.lead, p.lede, p.leed {\n"
                + "                font-size: 18px;\n"
                + "                line-height:21px;\n"
                + "            }\n"
                + "\n"
                + "            p { \n"
                + "                margin-bottom: 10px;\n"
                + "            }\n"
                + "\n"
                + "            small {\n"
                + "                font-size: 10px;\n"
                + "            }\n"
                + "\n"
                + "            a {\n"
                + "                color: #2ba6cb; \n"
                + "                text-decoration: none;\n"
                + "            }\n"
                + "\n"
                + "            a:hover { \n"
                + "                color: #2795b6 !important;\n"
                + "            }\n"
                + "\n"
                + "            a:active { \n"
                + "                color: #2795b6 !important;\n"
                + "            }\n"
                + "\n"
                + "            a:visited { \n"
                + "                color: #2ba6cb !important;\n"
                + "            }\n"
                + "\n"
                + "            h1 a, \n"
                + "            h2 a, \n"
                + "            h3 a, \n"
                + "            h4 a, \n"
                + "            h5 a, \n"
                + "            h6 a {\n"
                + "                color: #2ba6cb;\n"
                + "            }\n"
                + "\n"
                + "            h1 a:active, \n"
                + "            h2 a:active,  \n"
                + "            h3 a:active, \n"
                + "            h4 a:active, \n"
                + "            h5 a:active, \n"
                + "            h6 a:active { \n"
                + "                color: #2ba6cb !important; \n"
                + "            } \n"
                + "\n"
                + "            h1 a:visited, \n"
                + "            h2 a:visited,  \n"
                + "            h3 a:visited, \n"
                + "            h4 a:visited, \n"
                + "            h5 a:visited, \n"
                + "            h6 a:visited { \n"
                + "                color: #2ba6cb !important; \n"
                + "            } \n"
                + "\n"
                + "            /* Panels */\n"
                + "\n"
                + "            .panel {\n"
                + "                background: #f2f2f2;\n"
                + "                border: 1px solid #d9d9d9;\n"
                + "                padding: 10px !important;\n"
                + "            }\n"
                + "\n"
                + "            .sub-grid table {\n"
                + "                width: 100%;\n"
                + "            }\n"
                + "\n"
                + "            .sub-grid td.sub-columns {\n"
                + "                padding-bottom: 0;\n"
                + "            }\n"
                + "\n"
                + "            /* Buttons */\n"
                + "\n"
                + "            table.button,\n"
                + "            table.tiny-button,\n"
                + "            table.small-button,\n"
                + "            table.medium-button,\n"
                + "            table.large-button {\n"
                + "                width: 100%;\n"
                + "                overflow: hidden;\n"
                + "            }\n"
                + "\n"
                + "            table.button td,\n"
                + "            table.tiny-button td,\n"
                + "            table.small-button td,\n"
                + "            table.medium-button td,\n"
                + "            table.large-button td {\n"
                + "                display: block;\n"
                + "                width: auto !important;\n"
                + "                text-align: center;\n"
                + "                background: #2ba6cb;\n"
                + "                border: 1px solid #2284a1;\n"
                + "                color: #ffffff;\n"
                + "                padding: 8px 0;\n"
                + "            }\n"
                + "\n"
                + "            table.tiny-button td {\n"
                + "                padding: 5px 0 4px;\n"
                + "            }\n"
                + "\n"
                + "            table.small-button td {\n"
                + "                padding: 8px 0 7px;\n"
                + "            }\n"
                + "\n"
                + "            table.medium-button td {\n"
                + "                padding: 12px 0 10px;\n"
                + "            }\n"
                + "\n"
                + "            table.large-button td {\n"
                + "                padding: 21px 0 18px;\n"
                + "            }\n"
                + "\n"
                + "            table.button td a,\n"
                + "            table.tiny-button td a,\n"
                + "            table.small-button td a,\n"
                + "            table.medium-button td a,\n"
                + "            table.large-button td a {\n"
                + "                font-weight: bold;\n"
                + "                text-decoration: none;\n"
                + "                font-family: Helvetica, Arial, sans-serif;\n"
                + "                color: #ffffff;\n"
                + "                font-size: 16px;\n"
                + "            }\n"
                + "\n"
                + "            table.tiny-button td a {\n"
                + "                font-size: 12px;\n"
                + "                font-weight: normal;\n"
                + "            }\n"
                + "\n"
                + "            table.small-button td a {\n"
                + "                font-size: 16px;\n"
                + "            }\n"
                + "\n"
                + "            table.medium-button td a {\n"
                + "                font-size: 20px;\n"
                + "            }\n"
                + "\n"
                + "            table.large-button td a {\n"
                + "                font-size: 24px;\n"
                + "            }\n"
                + "\n"
                + "            table.button:hover td,\n"
                + "            table.button:visited td,\n"
                + "            table.button:active td {\n"
                + "                background: #2795b6 !important;\n"
                + "            }\n"
                + "\n"
                + "            table.button:hover td a,\n"
                + "            table.button:visited td a,\n"
                + "            table.button:active td a {\n"
                + "                color: #fff !important;\n"
                + "            }\n"
                + "\n"
                + "            table.button:hover td,\n"
                + "            table.tiny-button:hover td,\n"
                + "            table.small-button:hover td,\n"
                + "            table.medium-button:hover td,\n"
                + "            table.large-button:hover td {\n"
                + "                background: #2795b6 !important;\n"
                + "            }\n"
                + "\n"
                + "            table.button:hover td a,\n"
                + "            table.button:active td a,\n"
                + "            table.button td a:visited,\n"
                + "            table.tiny-button:hover td a,\n"
                + "            table.tiny-button:active td a,\n"
                + "            table.tiny-button td a:visited,\n"
                + "            table.small-button:hover td a,\n"
                + "            table.small-button:active td a,\n"
                + "            table.small-button td a:visited,\n"
                + "            table.medium-button:hover td a,\n"
                + "            table.medium-button:active td a,\n"
                + "            table.medium-button td a:visited,\n"
                + "            table.large-button:hover td a,\n"
                + "            table.large-button:active td a,\n"
                + "            table.large-button td a:visited {\n"
                + "                color: #ffffff !important; \n"
                + "            }\n"
                + "\n"
                + "            table.secondary td {\n"
                + "                background: #e9e9e9;\n"
                + "                border-color: #d0d0d0;\n"
                + "                color: #555;\n"
                + "            }\n"
                + "\n"
                + "            table.secondary td a {\n"
                + "                color: #555;\n"
                + "            }\n"
                + "\n"
                + "            table.secondary:hover td {\n"
                + "                background: #d0d0d0 !important;\n"
                + "                color: #555;\n"
                + "            }\n"
                + "\n"
                + "            table.secondary:hover td a,\n"
                + "            table.secondary td a:visited,\n"
                + "            table.secondary:active td a {\n"
                + "                color: #555 !important;\n"
                + "            }\n"
                + "\n"
                + "            table.success td {\n"
                + "                background: #5da423;\n"
                + "                border-color: #457a1a;\n"
                + "            }\n"
                + "\n"
                + "            table.success:hover td {\n"
                + "                background: #457a1a !important;\n"
                + "            }\n"
                + "\n"
                + "            table.alert td {\n"
                + "                background: #c60f13;\n"
                + "                border-color: #970b0e;\n"
                + "            }\n"
                + "\n"
                + "            table.alert:hover td {\n"
                + "                background: #970b0e !important;\n"
                + "            }\n"
                + "\n"
                + "            table.radius td {\n"
                + "                -webkit-border-radius: 3px;\n"
                + "                -moz-border-radius: 3px;\n"
                + "                border-radius: 3px;\n"
                + "            }\n"
                + "\n"
                + "            table.round td {\n"
                + "                -webkit-border-radius: 500px;\n"
                + "                -moz-border-radius: 500px;\n"
                + "                border-radius: 500px;\n"
                + "            }\n"
                + "\n"
                + "            /* Outlook First */\n"
                + "\n"
                + "            body.outlook p {\n"
                + "                display: inline !important;\n"
                + "            }\n"
                + "\n"
                + "            /*  Media Queries */\n"
                + "\n"
                + "            @media only screen and (max-width: 600px) {\n"
                + "\n"
                + "                table[class=\"body\"] img {\n"
                + "                    width: auto !important;\n"
                + "                    height: auto !important;\n"
                + "                }\n"
                + "\n"
                + "                table[class=\"body\"] center {\n"
                + "                    min-width: 0 !important;\n"
                + "                }\n"
                + "\n"
                + "                table[class=\"body\"] .container {\n"
                + "                    width: 95% !important;\n"
                + "                }\n"
                + "\n"
                + "                table[class=\"body\"] .row {\n"
                + "                    width: 100% !important;\n"
                + "                    display: block !important;\n"
                + "                }\n"
                + "\n"
                + "                table[class=\"body\"] .wrapper {\n"
                + "                    display: block !important;\n"
                + "                    padding-right: 0 !important;\n"
                + "                }\n"
                + "\n"
                + "                table[class=\"body\"] .columns,\n"
                + "                table[class=\"body\"] .column {\n"
                + "                    table-layout: fixed !important;\n"
                + "                    float: none !important;\n"
                + "                    width: 100% !important;\n"
                + "                    padding-right: 0px !important;\n"
                + "                    padding-left: 0px !important;\n"
                + "                    display: block !important;\n"
                + "                }\n"
                + "\n"
                + "                table[class=\"body\"] .wrapper.first .columns,\n"
                + "                table[class=\"body\"] .wrapper.first .column {\n"
                + "                    display: table !important;\n"
                + "                }\n"
                + "\n"
                + "                table[class=\"body\"] table.columns td,\n"
                + "                table[class=\"body\"] table.column td {\n"
                + "                    width: 100% !important;\n"
                + "                }\n"
                + "\n"
                + "                table[class=\"body\"] .columns td.one,\n"
                + "                table[class=\"body\"] .column td.one { width: 8.333333% !important; }\n"
                + "                table[class=\"body\"] .columns td.two,\n"
                + "                table[class=\"body\"] .column td.two { width: 16.666666% !important; }\n"
                + "                table[class=\"body\"] .columns td.three,\n"
                + "                table[class=\"body\"] .column td.three { width: 25% !important; }\n"
                + "                table[class=\"body\"] .columns td.four,\n"
                + "                table[class=\"body\"] .column td.four { width: 33.333333% !important; }\n"
                + "                table[class=\"body\"] .columns td.five,\n"
                + "                table[class=\"body\"] .column td.five { width: 41.666666% !important; }\n"
                + "                table[class=\"body\"] .columns td.six,\n"
                + "                table[class=\"body\"] .column td.six { width: 50% !important; }\n"
                + "                table[class=\"body\"] .columns td.seven,\n"
                + "                table[class=\"body\"] .column td.seven { width: 58.333333% !important; }\n"
                + "                table[class=\"body\"] .columns td.eight,\n"
                + "                table[class=\"body\"] .column td.eight { width: 66.666666% !important; }\n"
                + "                table[class=\"body\"] .columns td.nine,\n"
                + "                table[class=\"body\"] .column td.nine { width: 75% !important; }\n"
                + "                table[class=\"body\"] .columns td.ten,\n"
                + "                table[class=\"body\"] .column td.ten { width: 83.333333% !important; }\n"
                + "                table[class=\"body\"] .columns td.eleven,\n"
                + "                table[class=\"body\"] .column td.eleven { width: 91.666666% !important; }\n"
                + "                table[class=\"body\"] .columns td.twelve,\n"
                + "                table[class=\"body\"] .column td.twelve { width: 100% !important; }\n"
                + "\n"
                + "                table[class=\"body\"] td.offset-by-one,\n"
                + "                table[class=\"body\"] td.offset-by-two,\n"
                + "                table[class=\"body\"] td.offset-by-three,\n"
                + "                table[class=\"body\"] td.offset-by-four,\n"
                + "                table[class=\"body\"] td.offset-by-five,\n"
                + "                table[class=\"body\"] td.offset-by-six,\n"
                + "                table[class=\"body\"] td.offset-by-seven,\n"
                + "                table[class=\"body\"] td.offset-by-eight,\n"
                + "                table[class=\"body\"] td.offset-by-nine,\n"
                + "                table[class=\"body\"] td.offset-by-ten,\n"
                + "                table[class=\"body\"] td.offset-by-eleven {\n"
                + "                    padding-left: 0 !important;\n"
                + "                }\n"
                + "\n"
                + "                table[class=\"body\"] table.columns td.expander {\n"
                + "                    width: 1px !important;\n"
                + "                }\n"
                + "\n"
                + "                table[class=\"body\"] .right-text-pad,\n"
                + "                table[class=\"body\"] .text-pad-right {\n"
                + "                    padding-left: 10px !important;\n"
                + "                }\n"
                + "\n"
                + "                table[class=\"body\"] .left-text-pad,\n"
                + "                table[class=\"body\"] .text-pad-left {\n"
                + "                    padding-right: 10px !important;\n"
                + "                }\n"
                + "\n"
                + "                table[class=\"body\"] .hide-for-small,\n"
                + "                table[class=\"body\"] .show-for-desktop {\n"
                + "                    display: none !important;\n"
                + "                }\n"
                + "\n"
                + "                table[class=\"body\"] .show-for-small,\n"
                + "                table[class=\"body\"] .hide-for-desktop {\n"
                + "                    display: inherit !important;\n"
                + "                }\n"
                + "            }\n"
                + "\n"
                + "        </style>\n"
                + "        <style>\n"
                + "\n"
                + "            table.facebook td {\n"
                + "                background: #3b5998;\n"
                + "                border-color: #2d4473;\n"
                + "            }\n"
                + "\n"
                + "            table.facebook:hover td {\n"
                + "                background: #2d4473 !important;\n"
                + "            }\n"
                + "\n"
                + "            table.twitter td {\n"
                + "                background: #00acee;\n"
                + "                border-color: #0087bb;\n"
                + "            }\n"
                + "\n"
                + "            table.twitter:hover td {\n"
                + "                background: #0087bb !important;\n"
                + "            }\n"
                + "\n"
                + "            table.google-plus td {\n"
                + "                background-color: #DB4A39;\n"
                + "                border-color: #CC0000;\n"
                + "            }\n"
                + "\n"
                + "            table.google-plus:hover td {\n"
                + "                background: #CC0000 !important;\n"
                + "            }\n"
                + "\n"
                + "            .template-label {\n"
                + "                color: #000000;\n"
                + "                font-weight: bold;\n"
                + "                font-size: 11px;\n"
                + "            }\n"
                + "\n"
                + "            .callout .wrapper {\n"
                + "                padding-bottom: 20px;\n"
                + "            }\n"
                + "\n"
                + "            .callout .panel {\n"
                + "                background: #FFFFFF;\n"
                + "                border-color: #000000;\n"
                + "            }\n"
                + "\n"
                + "            .header {\n"
                + "                background: #999999;\n"
                + "            }\n"
                + "\n"
                + "            .footer .wrapper {\n"
                + "                background: #ebebeb;\n"
                + "            }\n"
                + "\n"
                + "            .footer h5 {\n"
                + "                padding-bottom: 10px;\n"
                + "            }\n"
                + "\n"
                + "            table.columns .text-pad {\n"
                + "                padding-left: 10px;\n"
                + "                padding-right: 10px;\n"
                + "            }\n"
                + "\n"
                + "            table.columns .left-text-pad {\n"
                + "                padding-left: 10px;\n"
                + "            }\n"
                + "\n"
                + "            table.columns .right-text-pad {\n"
                + "                padding-right: 10px;\n"
                + "            }\n"
                + "\n"
                + "            @media only screen and (max-width: 600px) {\n"
                + "\n"
                + "                table[class=\"body\"] .right-text-pad {\n"
                + "                    padding-left: 10px !important;\n"
                + "                }\n"
                + "\n"
                + "                table[class=\"body\"] .left-text-pad {\n"
                + "                    padding-right: 10px !important;\n"
                + "                }\n"
                + "            }\n"
                + "\n"
                + "            #apDiv1 {\n"
                + "                position: absolute;\n"
                + "                width: 146px;\n"
                + "                height: 132px;\n"
                + "                z-index: 1;\n"
                + "                left: 455px;\n"
                + "                top: 33px;\n"
                + "            }\n"
                + "        </style>\n"
                + "    </head>\n"
                + "    <body>\n"
                + "        <table class=\"body block-grid\">\n"
                + "            <tr>\n"
                + "                <td class=\"center\" align=\"center\" valign=\"top\">\n"
                + "                    <center>\n"
                + "\n"
                + "                        <table class=\"row header\">\n"
                + "                            <tr>\n"
                + "                                <td align=\"center\" bgcolor=\"#ffffff\" class=\"center\">\n"
                + "                                    <center>\n"
                + "                                        <table class=\"container\">\n"
                + "                                            <tr bgcolor=\"#FFFFFF\">\n"
                + "                                                <td class=\"wrapper last\">\n"
                + "\n"
                + "                                                    <table class=\"twelve columns\">\n"
                + "                                                        <tr>\n"
                + "                                                            <td class=\"six sub-columns\">\n"
                + "                                                                <img width=\"349px\" height=\"126px\" src=\"https://s21.postimg.org/5mkelwj2f/hogar.png\"/>\n"
                + "                                                            </td>\n"
                + "                                                        </tr>\n"
                + "                                                    </table>\n"
                + "                                                </td>\n"
                + "                                            </tr>\n"
                + "                                        </table>\n"
                + "                                    </center>\n"
                + "                                </td>\n"
                + "                            </tr>\n"
                + "                        </table>\n"
                + "                        <table width=\"754\" class=\"container\">\n"
                + "                            <tr bgcolor=\"#ffffff\">\n"
                + "                                <td>\n"
                + "                                    <table class=\"row\">\n"
                + "                                        <tr>\n"
                + "                                            <td class=\"wrapper last\">\n"
                + "\n"
                + "                                                <table class=\"twelve columns\">\n"
                + "                                                    <tr>\n"
                + "                                                        <td>\n"
                + "                                                            <h1>Saludos Cordiales</h1>\n"
                + "                                                            <p class=\"lead\">XNombreX</p>\n"
                + "                                                            <p class=\"lead\">&nbsp;</p>\n"
                + "                                                            <p class=\"lead\"  >\n"
                + "                                                                Estimado usuario por medio de la presente confirmanos cualquier pago o multa del lugar de su vivienda: </p>\n"
                + "\n"
                + "                                                            <table width=\"562\" border=\"0\">\n"
                + "                                                                <tr>\n"
                + "                                                                    <th width=\"148\" scope=\"row\">Lugar:</th>\n"
                + "                                                                    <td width=\"404\">XLugarX</td>\n"
                + "                                                                </tr>\n"
                + "                                                                <tr>\n"
                + "                                                                    <th width=\"148\" scope=\"row\">Asunto:</th>\n"
                + "                                                                    <td width=\"404\">XAsuntoX</td>\n"
                + "                                                                </tr>\n"
                + "                                                                <tr>\n"
                + "                                                                    <th scope=\"row\">Forma de Pago:</th>\n"
                + "                                                                    <td>XFormaX</td>\n"
                + "                                                                </tr>\n"
                + "                                                                <tr>\n"
                + "                                                                    <th scope=\"row\">Valor:</th>\n"
                + "                                                                    <td>XValorX</td>\n"
                + "                                                                </tr>\n"
                + "                                                                <tr>\n"
                + "                                                                    <th scope=\"row\">Fecha:</th>\n"
                + "                                                                    <td>XFechaX</td>\n"
                + "                                                                </tr>\n"
                + "                                                            </table></td>\n"
                + "                                                    </tr>\n"
                + "                                                </table>\n"
                + "\n"
                + "                                            </td>\n"
                + "                                        </tr>\n"
                + "                                    </table>\n"
                + "\n"
                + "                                    <table class=\"row callout\">\n"
                + "                                        <tr bgcolor=\"#FFFFFF\">\n"
                + "                                            <td bgcolor=\"#ECF8FF\" class=\"wrapper last\">\n"
                + "\n"
                + "                                                <table width=\"621\" class=\"twelve columns\">\n"
                + "                                                    <tr>\n"
                + "                                                        <td bgcolor=\"#FFFFFF\" class=\"panel\">\n"
                + "                                                            <p>Por favor brindar atención a la presente para la confirmacion de multas y pagos de su vivienda.</p>\n"
                + "                                                        </td>\n"
                + "                                                    </tr>\n"
                + "                                                </table>\n"
                + "\n"
                + "                                            </td>\n"
                + "                                        </tr>\n"
                + "                                    </table>\n"
                + "\n"
                + "                                    <table class=\"row\">\n"
                + "                                        <tr>\n"
                + "                                            <td class=\"wrapper last\">\n"
                + "\n"
                + "                                                <table class=\"twelve columns\">\n"
                + "                                                    <tr>\n"
                + "                                                        <td align=\"center\">\n"
                + "                                                            <center>\n"
                + "                                                                <p style=\"text-align:center;\"><a href=\"http://softlutions.ec/\">Software</a> | <a href=\"http://softlutions.ec/\">Conjuntos</a></p>\n"
                + "                                                            </center>\n"
                + "                                                        </td>\n"
                + "                                                    </tr>\n"
                + "                                                </table>\n"
                + "\n"
                + "                                            </td>\n"
                + "                                        </tr>\n"
                + "                                    </table>\n"
                + "                                </td>\n"
                + "                            </tr>\n"
                + "                        </table>\n"
                + "\n"
                + "                    </center>\n"
                + "                </td>\n"
                + "            </tr>\n"
                + "        </table>\n"
                + "    </body>\n"
                + "</html>";
        return html;
    }
}
